### ISSUE TITLE
[New, Proposed] Froglight

### ISSUE THREAD

**Issue by keijodputt** [EarthPol/EarthPolRecipes#2]
Light sources such as froglight are pretty popular. Since there is no Nether, there are no magma cubes, hence frogs can't produce froglight.

I propose that mechanics can be altered so we can have froglight (ochre, pearlescent, verdant):
a) by modifying frogs, so they can eat slimes instead, or
b) by craft recipe, with a glowstone block, magma cream, and red dye for ochre, white dye for pearlescent, green dye for verdant.

**Comment by Bustun01** [comment]
Froglight recipes were added. They can be found on the EarthPol wiki: https://earthpol.fandom.com/wiki/Custom_Crafting_Recipes
